
partmenu:dialog{
     key = "title";
     :row{
//        :boxed_row{
//                      label="目錄";
                   :boxed_column{
                            :button{
                                    label="常用軸承";
                                    key="func1";
                                   }
                            :button{
                                    label="螺栓";
                                    key="func3";
                                   }
                            :button{
                                    label="彈簧";
                                    key="func5";
                                   }
                            :button{
                                    label="銷";
                                    key="func7";
                                   }
                            :button{
                                    label="傳動齒輪";
                                    key="func9";
                                   }
                            :button{
                                    label="扣環";
                                    key="func11";
                                   }
                            :button{
                                    label="皮帶輪";
                                    key="func13";
                                   }
                            :button{
                                    label="輕型鋼";
                                    key="func15";
                                   }
                            :button{
                                    label="";
                                    key="func17";
                                   }
                            }//end of boxed_column
                        :boxed_column{
                            :button{
                                    label="連座軸承";
                                    key="func2";
                                   }
                            :button{
                                    label="華司(墊圈)";
                                    key="func4";
                                   }
                            :button{
                                    label="型鋼系列";
                                    key="func6";
                                   }
                            :button{
                                    label="油 封";
                                    key="func8";
                                   }
                            :button{
                                    label="鍵";
                                    key="func10";
                                   }
                            :button{
                                    label="皮帶";
                                    key="func12";
                                   }
                            :button{
                                    label="螺帽";
                                    key="func14";
                                   }
                            :button{
                                    label="";
                                    key="func16";
                                   }
                            :button{
                                    label="";
                                    key="func18";
                                   }
                            }//end of boxed_column
// }//end of boxed_row
          :boxed_column{
                       label="請選擇一項";
                       :row{
                            :image_button{
                                          key="sld11";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld12";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld13";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld14";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button

                       }//end of row
                       :row{
                           :text {
                                  key = "sld11_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld12_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld13_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld14_txt";
                                  width=16;
                                 }//text
                           }//end of row
                       :row{
                            :image_button{
                                          key="sld21";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld22";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld23";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld24";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button

                       }//end of row
                       :row{
                           :text {
                                  key = "sld21_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld22_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld23_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld24_txt";
                                  width=16;
                                 }//text
                           }//end of row
                       :row{
                            :image_button{
                                          key="sld31";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld32";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld33";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld34";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button

                       }//end of row
                       :row{
                           :text {
                                  key = "sld31_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld32_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld33_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld34_txt";
                                  width=16;
                                 }//text
                           }//end of row
                       :row{
                            :image_button{
                                          key="sld41";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld42";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld43";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld44";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button

                       }//end of row
                       :row{
                           :text {
                                  key = "sld41_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld42_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld43_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld44_txt";
                                  width=16;
                                 }//text
                           }//end of row
                      }//end of boxed_column
         }//end of row
//       :row{
//             :column{
//                    :text{key="func_tile";}
                      ok_only;
//                    }
//               :image{
//                      key="powersoft";
//                      height =6;
//                      width=5;
//                      color =7;
//                     }
//              }//end of row
}

partmenu2:dialog{
     key = "title";
     :row{
          :boxed_column{
                        label="目錄";
                        :row{
                            :button{
                                    label="鑽孔攻牙";
                                    key="func1";
                                   }
                            :button{
                                    label="加工符號";
                                    key="func2";
                                   }
                            }//end of row
                        :row{
                            :button{
                                    label="尺寸公差";
                                    key="func3";
                                   }
                            :button{
                                    label="形狀公差";
                                    key="func4";
                                   }
                            }//end of row
                        :row{
                            :button{
                                    label="螺栓螺帽";
                                    key="func5";
                                   }
                            :button{
                                    label=" 平帶輪 ";
                                    key="func6";
                                   }
                            }//end of row
                        :row{
                            :button{
                                    label="方形平板";
                                    key="func7";
                                   }
                            :button{
                                    label="";
                                    key="func8";
                                   }
                            }//end of row
                        :row{
                            :button{
                                    label="";
                                    key="func9";
                                   }
                            :button{
                                    label="";
                                    key="func10";
                                   }
                            }//end of row
                        :row{
                            :button{
                                    label="";
                                    key="func11";
                                   }
                            :button{
                                    label="";
                                    key="func12";
                                   }
                            }//end of row
                        :row{
                            :button{
                                    label="";
                                    key="func13";
                                   }
                            :button{
                                    label="";
                                    key="func14";
                                   }
                            }//end of row
                        :row{
                            :button{
                                    label="";
                                    key="func15";
                                   }
                            :button{
                                    label="";
                                    key="func16";
                                   }
                            }//end of row
                       }//end of boxed_column
          :boxed_column{
                       label="請選擇一項";
                       :row{
                            :image_button{
                                          key="sld11";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld12";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld13";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld14";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button

                       }//end of row
                       :row{
                           :text {
                                  key = "sld11_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld12_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld13_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld14_txt";
                                  width=16;
                                 }//text
                           }//end of row
                       :row{
                            :image_button{
                                          key="sld21";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld22";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld23";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld24";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button

                       }//end of row
                       :row{
                           :text {
                                  key = "sld21_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld22_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld23_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld24_txt";
                                  width=16;
                                 }//text
                           }//end of row
                       :row{
                            :image_button{
                                          key="sld31";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld32";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld33";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld34";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button

                       }//end of row
                       :row{
                           :text {
                                  key = "sld31_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld32_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld33_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld34_txt";
                                  width=16;
                                 }//text
                           }//end of row
                       :row{
                            :image_button{
                                          key="sld41";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld42";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld43";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button
                            :image_button{
                                          key="sld44";
                                          height =6;
                                          width=16;
                                          color =-2;} //end of image_button

                       }//end of row
                       :row{
                           :text {
                                  key = "sld41_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld42_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld43_txt";
                                  width=16;
                                 }//text
                           :text {
                                  key = "sld44_txt";
                                  width=16;
                                 }//text
                           }//end of row
                      }//end of boxed_column
         }//end of row
         :row{
               :column{
                      :text{key="func_tile";}
                      ok_only;
                      }
                 :image{
                        key="powersoft";
                        height =6;
                        width=5;
                        color =7;
                       }
                }//end of row
}
