
userblku:dialog{
          key = "showhead";
          :row{
               :text {
                      key = "item_path";
                      width=20;
                     }//text
                       :text {
                             key = "block_note";
                             value="檔名顯示處!";
                             width=10;
                             }//text


             }//end of row
          :row{
               :popup_list{
                           label="頁數";
                           key= "page";
                           edit_width=30;
                          }
//                               label = "符號插入方式";
                                 :toggle{
                                         label= "爆  炸";
                                         key = "explod";
                                        }
                        :button {
                                 label="圖形放大";
                                 key="zoom_block";
                                }
                        :text{key="message";
                              width=30;
                             }
             //:spacer{width=20;}

              }
          :row{
            :column{
                    :image_button{
                                  key="sld11";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt11";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld12";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt12";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld13";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt13";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld14";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt14";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld15";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt15";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld16";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt16";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld17";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt17";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld18";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt18";}
                   }//end of column

          }//row
          :row{
            :column{
                    :image_button{
                                  key="sld21";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt21";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld22";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt22";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld23";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt23";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld24";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt24";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld25";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt25";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld26";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt26";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld27";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt27";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld28";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt28";}
                   }//end of column

          }//row
          :row{
            :column{
                    :image_button{
                                  key="sld31";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt31";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld32";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt32";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld33";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt33";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld34";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt34";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld35";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt35";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld36";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt36";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld37";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt37";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld38";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt38";}
                   }//end of column

          }//row
          :row{
            :column{
                    :image_button{
                                  key="sld41";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt41";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld42";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt42";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld43";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt43";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld44";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt44";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld45";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt45";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld46";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt46";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld47";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt47";}
                   }//end of column
            :column{
                    :image_button{
                                  key="sld48";
                                  height =4;
                                  width=12;
                                  color =-2;
                                 }
                    :edit_box{edit_width=10;
                              key="txt48";}
                   }//end of column


          }//row

//        :row{
//          :column{
//           :boxed_column{
//                               label = "符號插入方式";
//                               :toggle{
//                                       label= "爆  炸";
//                                       key = "explod";
//                                      }
//
//
//                      :text{label="註：爆炸方式插入的";}
//                      :text{label="符號無法作資料清單";}
//                //    :button{
//                //            label="查詢各頁註解";
//                //            key="total_page_memo";
//                //           }
//                      :button {
//                               label="圖形放大";
//                               key="zoom_block";
//                              }
//
//                              }//boxed_column
//           }//column
//           :row{
//              :column{
                :boxed_column{
                    //  :text{ key="bname";
                    //         width=40;
                    //       }
                        label="圖塊資料";
                     :row{
                        :text{ key="data1";
                               width=10;
                             }
                        :text{ key="data2";
                               width=10;
                             }
                        :text{ key="data3";
                               width=20;
                             }
                        :text{ key="data4";
                               width=10;
                             }
                        :text{ key="data5";
                               width=10;
                             }
                      }//end of row
                        :text{ key="blocknote";
                               width=10;
                             }
                   //   :text{ key="message"; }
                       }//end of row
//                     }//end column
//           }//end boxed_row
//        :column{
//                :button {
//                         label="藝祥資訊";
//                         key="piec";
//                        }
//                 :text{key="right1";}
//                 :text{key="right2";}
                  ok_cancel;
//
//               }//end of column
//        }//end row
       spacer_1;
//     ok_cancel;
}


zoomblock:dialog{
               :image{
                      key="sld_name";
                      height=30;
                      width=80;
                      color =-2;
                      }
               ok_only;
}

pgmemo:dialog{
         :list_box{
                     label= "頁數    各頁註解瀏覽";
                     key= "pagememo";
                     width=60;
                     }
          ok_only;
}
