

tol:dialog{key="title";
           :row{
                :list_box{
                          label="尺寸之區分";
                          key="holedia";
                          height=29;
                          width=14;
                         }
                :column{
                        :row{
                             :column{
                                     :radio_button{label="B10";
                     //                            fixed_width_font=true;
                                                   key="B10";
                                                  }//end of radio_button
                                     :row{
                                         :text{label="上公差:";
                  //                                 fixed_width_font=true;
                                               width=8;}
                                         :text{key="b10u";
                                               width=8;}
                                         }//end of row
                                     :row{
                                         :text{label="下公差:";
                   //                                fixed_width_font=true;
                                               width=8;}
                                         :text{key="b10d";
                                               width=8;}
                                         }//end of row
                                     }//end of boxed_column
                             :column{
                                           :radio_button{label="C9";
                                                         key="C9";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="c9u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="c9d";
                                                     width=8;}
                                               }//end of row
                                          }//end of column
                             :column{
                                           :radio_button{label="C10";
                                                         key="C10";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="c10u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="c10d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="D8";
                                                         key="D8";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="d8u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="d8d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="D9";
                                                         key="D9";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="d9u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="d9d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                            }//end of row
                        :row{
                             :column{
                                          :radio_button{label="D10";
                                                        key="D10";
                                                       }//end of radio_button
                                          :row{
                                              :text{label="上公差:";
                                                    width=8;}
                                              :text{key="d10u";
                                                    width=8;}
                                              }//end of row
                                          :row{
                                              :text{label="下公差:";
                                                    width=8;}
                                              :text{key="d10d";
                                                    width=8;}
                                              }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="E7";
                                                         key="E7";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="e7u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="e7d";
                                                     width=8;}
                                               }//end of row
                                          }//end of column
                             :column{
                                           :radio_button{label="E8";
                                                         key="E8";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="e8u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="e8d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="E9";
                                                         key="E9";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="e9u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="e9d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="F6";
                                                         key="F6";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="f6u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="f6d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                            }//end of row
                        :row{
                             :column{
                                          :radio_button{label="F7";
                                                        key="F7";
                                                       }//end of radio_button
                                          :row{
                                              :text{label="上公差:";
                                                    width=8;}
                                              :text{key="f7u";
                                                    width=8;}
                                              }//end of row
                                          :row{
                                              :text{label="下公差:";
                                                    width=8;}
                                              :text{key="f7d";
                                                    width=8;}
                                              }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="F8";
                                                         key="F8";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="f8u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="f8d";
                                                     width=8;}
                                               }//end of row
                                          }//end of column
                             :column{
                                           :radio_button{label="G6";
                                                         key="G6";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="g6u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="g6d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="G7";
                                                         key="G7";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="g7u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="g7d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="H6";
                                                         key="H6";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="h6u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="h6d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                            }//end of row
                        :row{
                             :column{
                                          :radio_button{label="H7";
                                                        key="H7";
                                                       }//end of radio_button
                                          :row{
                                              :text{label="上公差:";
                                                    width=8;}
                                              :text{key="h7u";
                                                    width=8;}
                                              }//end of row
                                          :row{
                                              :text{label="下公差:";
                                                    width=8;}
                                              :text{key="h7d";
                                                    width=8;}
                                              }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="H8";
                                                         key="H8";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="h8u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="h8d";
                                                     width=8;}
                                               }//end of row
                                          }//end of column
                             :column{
                                           :radio_button{label="H9";
                                                         key="H9";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="h9u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="h9d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="H10";
                                                         key="H10";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="h10u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="h10d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="Js6";
                                                         key="Js6";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="js6u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="js6d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                            }//end of row
                        :row{
                             :column{
                                          :radio_button{label="Js7";
                                                        key="Js7";
                                                       }//end of radio_button
                                          :row{
                                              :text{label="上公差:";
                                                    width=8;}
                                              :text{key="js7u";
                                                    width=8;}
                                              }//end of row
                                          :row{
                                              :text{label="下公差:";
                                                    width=8;}
                                              :text{key="js7d";
                                                    width=8;}
                                              }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="K6";
                                                         key="K6";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="k6u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="k6d";
                                                     width=8;}
                                               }//end of row
                                          }//end of column
                             :column{
                                           :radio_button{label="K7";
                                                         key="K7";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="k7u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="k7d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="M6";
                                                         key="M6";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="m6u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="m6d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="M7";
                                                         key="M7";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="m7u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="m7d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                            }//end of row
                        :row{
                             :column{
                                          :radio_button{label="N6";
                                                        key="N6";
                                                       }//end of radio_button
                                          :row{
                                              :text{label="上公差:";
                                                    width=8;}
                                              :text{key="n6u";
                                                    width=8;}
                                              }//end of row
                                          :row{
                                              :text{label="下公差:";
                                                    width=8;}
                                              :text{key="n6d";
                                                    width=8;}
                                              }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="N7";
                                                         key="N7";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="n7u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="n7d";
                                                     width=8;}
                                               }//end of row
                                          }//end of column
                             :column{
                                           :radio_button{label="P6";
                                                         key="P6";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="p6u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="p6d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="P7";
                                                         key="P7";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="p7u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="p7d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="R7";
                                                         key="R7";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="r7u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="r7d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                            }//end of row
                        :row{
                             :column{
                                          :radio_button{label="S7";
                                                        key="S7";
                                                       }//end of radio_button
                                          :row{
                                              :text{label="上公差:";
                                                    width=8;}
                                              :text{key="s7u";
                                                    width=8;}
                                              }//end of row
                                          :row{
                                              :text{label="下公差:";
                                                    width=8;}
                                              :text{key="s7d";
                                                    width=8;}
                                              }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="T7";
                                                         key="T7";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="t7u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="t7d";
                                                     width=8;}
                                               }//end of row
                                          }//end of column
                             :column{
                                           :radio_button{label="U7";
                                                         key="U7";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="u7u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="u7d";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                             :column{
                                           :radio_button{label="X7";
                                                         key="X7";
                                                        }//end of radio_button
                                           :row{
                                               :text{label="上公差:";
                                                     width=8;}
                                               :text{key="x7u";
                                                     width=8;}
                                               }//end of row
                                           :row{
                                               :text{label="下公差:";
                                                     width=8;}
                                               :text{key="x7dwn val";
                                                     width=8;}
                                               }//end of row
                                          }//end of boxed_column
                            }//end of row

                       }//end of column

               }//end of row


       ok_cancel;
       errtile;
}//end of dialog


